config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  #routes.rb

  resources :artigos

  root 'artigos#index' #artigos controller com a acao index que esta em controller/artigos_controller
  get 'sobre' => 'artigos#sobre'



end

app/models/artigo.rb
class Artigo < ActiveRecord::Base

	belongs_to :usuario
	belongs_to :categoria


end

app/models/categoria.rb
class Categoria < ActiveRecord::Base

	has_many :artigos

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :artigos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
	before_action :achar_artigo, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_usuario!, except: [:index, :show]
	#se usuario quiser entrar ele nao ser redirecionado para o sign up
	def index
		if params[:categoria].blank?
			@artigos = Artigo.all.order("created_at DESC")
		else
			@categoria_id = Categoria.find_by(nome: params[:categoria]).id
			@artigos = Artigo.where(categoria_id: @categoria_id).order("created_at DESC")
		end


	end
	#se nao estiver selecionado um artigo, ira listar todos
	#se nao, ira listar apenas daquela categoria

	def show
	end
	

	def new
		@artigo = current_usuario.artigos.build
	end

	def create
		@artigo = current_usuario.artigos.build(artigo_parametros)
		if @artigo.save
			redirect_to @artigo
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @artigo.update(artigo_parametros)
			redirect_to @artigo
		else
			render 'edit'
		end
	end

	def destroy
		@artigo.destroy
		redirect_to root_path
	end

	def sobre
	end

	private

	def artigo_parametros
		params.require(:artigo).permit(:Título, :Conteúdo, :categoria_id)
	end

	def achar_artigo
		@artigo = Artigo.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/views/artigos/_form.html.haml
%br
= simple_form_for @artigo do |f|
	%blockquote
		= f.collection_select :categoria_id, Categoria.all, :id, :Nome, { promt: "Selecione uma Categoria" }
	
	
	%blockquote
		= f.input :Título
	
	%blockquote
		= f.input :Conteúdo
	
	%blockquote
		= f.submit

	
	/o barra e comentario em haml, obs: se deixar sem o igual vira um print normal

app/views/artigos/edit.html.haml
%h1(align="center") Editar Artigo

= render 'form'

%br
%p(align="center")
	.btn-group
	= link_to "Voltar", root_path, class: "btn btn-info"
	
%br
%br
%br
%br
%br
%br
%br
%br
%br
%br

app/views/artigos/index.html.haml
- if usuario_signed_in?
	%b
		

- @artigos.each do |artigo|
	
	%h2
		= link_to artigo.Título, artigo
	
	%p 
		= truncate(artigo.Conteúdo, length: 100)
	
	%p(align="right")
		Publicado em 
		= artigo.created_at.strftime('%d %b de %Y')


%br
%br
%br
%b
	%p(align="left")
		.btn-group-lg		
		=link_to "Sobre o Discipule", "sobre", class: "btn btn-info"

app/views/artigos/new.html.haml
%h1(align="center") 

= render 'form'

%br
%p(align="center")
.btn-group
	= link_to "Voltar", root_path, class: "btn btn-info"

%br
%br

app/views/artigos/show.html.haml
%h1= @artigo.Título
%p= @artigo.Conteúdo


.btn-group
	= link_to "Editar", edit_artigo_path(@artigo), class: "btn btn-warning"
.btn-group
	= link_to "Deletar", artigo_path(@artigo), method: :delete, class: "btn btn-danger"	
.btn-group
	= link_to "Voltar", root_path, class: "btn btn-info"

%br
%br

app/views/artigos/sobre.html.haml
%h1(align="center") Sobre

%p(align="center")
	Universidade de Brasília
	%br
	Faculdade UnB Gama
	%br
	Engenharia de Software
	%br
	Orientação a Objetos
	%br
	Professor: Renato Coral
	%br
	%br

	Projeto: Discipule - Cadastro de Conteúdos Online
	%br
	Alunos: Eduardo Gomes, Miguel Pimentel, Daniel Moura
	%br
	%br
	Criado em
	%br
	09 de Dezembro de 2015



%p(align="center")
	.btn-group
	= link_to "Voltar", root_path, class: "btn btn-info"
%br
%br

app/views/layouts/application.html.haml
%html
%head
	%title Discipule -  Compartilhando conhecimentos
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default.navbar-fixed-top
		.container
			= link_to "Discipule", root_path, class: "navbar-brand"
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Publicar Conteúdo", new_artigo_path

	%p.notice= notice
	%p.alert= alert

	.container
		.row
			.col-md-8
				= yield
			.col-md-4
				%ul.list-group-item
					%li= link_to "Todos os artigos", root_path, class: "list-group-item"
					- Categoria.all.each do |categoria|
						%li= link_to categoria.Nome, artigos_path(categoria: categoria.Nome), class: "list-group-item"